### ISSUE TITLE
程序泛化性运用

### ISSUE THREAD

**Issue by Ezekiel-tyo** [wangyk55/FAKE-GYM-PASS#1]
请问这个程序可以套用到其他高校的体育系统吗（来自非计算机专业的小白的真诚询问
想利用一下其他学校的体育设施资源

**Comment by wangyk55** [comment]
> 请问这个程序可以套用到其他高校的体育系统吗（来自非计算机专业的小白的真诚询问 想利用一下其他学校的体育设施资源

可能不太方便...我相当于是照着我们学校的体育预订系统的界面描了一遍，然后把系统上显示对应信息的地方改成了可以自定义的。换个学校的话系统界面各个学校基本上都不一样，要套用的话可能还不如从头写一遍
