### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by reddew651** [wangyk55/FAKE-GYM-PASS#2]
预约场馆、预约时段可以增加选项，毕竟大部分都是一样的，不然就要每次手动输入

**Comment by wangyk55** [comment]
> 预约场馆、预约时段可以增加选项，毕竟大部分都是一样的，不然就要每次手动输入

其实这个一直在to do list里...因为懒所以一直拖着没做别骂了别骂了
主要是现在体育馆似乎开始随机抽人查码了，所以我觉得可能这个项目快凉了

**Comment by reddew651** [comment]
> > 预约场馆、预约时段可以增加选项，毕竟大部分都是一样的，不然就要每次手动输入
> 
> 其实这个一直在to do list里...因为懒所以一直拖着没做别骂了别骂了 主要是现在体育馆似乎开始随机抽人查码了，所以我觉得可能这个项目快凉了

哈哈哈哈，可惜我前几天才发现，挺好的项目，大佬nb

**Comment by wangyk55** [comment]
没关系，功能总是要做的，等我过两天闲了就来搞这个。另外你对学校查码有什么应对措施吗

**Comment by reddew651** [comment]
> 没关系，功能总是要做的，等我过两天闲了就来搞这个。另外你对学校查码有什么应对措施吗

这个倒真没什么办法，要是能把别人预定的码爬下来就好了，不然一扫就露馅
